// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-822f42986d2252fa",
		"oceanbase":     "src-d49b1212dc3346c0",
		"diros":         "src-22a4b34299187154",
		"starrocks":     "src-65477a224960f59d",
		"sphinx":        "src-1c1b19765e692f11",
		"sqlserver":     "src-cc53e70d2784f521",
		"sqlite":        "src-57fac714056114ae",
		"duckdb":        "src-7174570cd6754d5b",
		"dameng":        "src-590678175b8deabf",
		"kingbase":      "src-42bf641a9134b961",
		"highgo":        "src-a9692832576fc0e6",
		"vastbase":      "src-46569add912285d9",
		"opengauss":     "src-a48992f71d4cc044",
		"gaussdb":       "src-2c72f0a43bcc150c",
		"iris":          "src-3aed9c5e816a8cc6",
		"cache":         "src-3f93e9cc05473d9c",
		"mongodb":       "src-e5fc5615ca24eab7",
		"tdengine":      "src-05e4a3238a25ae69",
		"iotdb":         "src-87ed1ae56ef21500",
		"clickhouse":    "src-3b5663549034dc2a",
		"elasticsearch": "src-794fa2deb5da68b9",
		"trino":         "src-17a674871f8b9cd8",
	}
}
