// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-3f3dee273ac68e92",
		"oceanbase":     "src-627103ccac79b75e",
		"diros":         "src-57952815bb94dd38",
		"starrocks":     "src-167d118f5e31c9f8",
		"sphinx":        "src-0e12e7b83f23252b",
		"sqlserver":     "src-d9a98f26549fca3d",
		"sqlite":        "src-a7484815bc6e5a10",
		"duckdb":        "src-32d866af503e17e9",
		"dameng":        "src-e93141afeb398cd1",
		"kingbase":      "src-90d7de73618f2ed5",
		"highgo":        "src-2e5ae7ff92ac3bd1",
		"vastbase":      "src-8cb48a9d351f4d40",
		"opengauss":     "src-912ebe643e539ce2",
		"gaussdb":       "src-88bbe3384c962eea",
		"iris":          "src-b47455c1afe9a76c",
		"mongodb":       "src-9df66c9e6cab9a4c",
		"tdengine":      "src-a84dd33e6bd2de3c",
		"iotdb":         "src-1578f8a7ce75e718",
		"clickhouse":    "src-0d7d352facd26548",
		"elasticsearch": "src-4a5bc907239f83e3",
		"trino":         "src-646cc35c89d6e501",
	}
}
