// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-efd56ca5e3d273b3",
		"oceanbase":     "src-f07127471839ec48",
		"diros":         "src-ca5125076643f0de",
		"starrocks":     "src-9daef6f00e2da974",
		"sphinx":        "src-f421a75e918c350a",
		"sqlserver":     "src-1806196b9c1b91f3",
		"sqlite":        "src-903c60cd5af6224b",
		"duckdb":        "src-804baf6d4ff9f6eb",
		"dameng":        "src-5cd3247c0b27b8ef",
		"kingbase":      "src-b3bf65342e8a9b3d",
		"highgo":        "src-14e5b483a5a23a25",
		"vastbase":      "src-91e64569590efcf3",
		"opengauss":     "src-f680ed28b20393dc",
		"gaussdb":       "src-4723bae76cdce34d",
		"iris":          "src-d1d087fdb0767877",
		"cache":         "src-6b0f3ede07dd6715",
		"mongodb":       "src-697e552392cae8a3",
		"tdengine":      "src-e3d6c0927f1c47e4",
		"iotdb":         "src-5f12cab1ba9aa6aa",
		"clickhouse":    "src-71ecd38135529565",
		"elasticsearch": "src-b67cf825edd0b273",
		"trino":         "src-fd3021edd9f55051",
	}
}
